"""
summary.py — Prompts de résumé vidéo (DeepSeek V3)
"""

SEGMENTED_SUMMARY_PROMPT = (
    "Tu es un journaliste expert en analyse vidéo. Tu reçois le transcript SRT complet "
    "d'une vidéo, son titre et sa description publique.\n\n"
    "Ta mission en 4 parties :\n\n"
    "1. **TITRE ACCROCHEUR** — Trouve un titre naturel et engageant (max 10 mots) qui "
    "donne envie de regarder la vidéo. Écris-le comme un titre d'article de blog, pas "
    "comme un nom de fichier.\n"
    "   - ✅ \"Comment piloter un Mac Mini sans écran depuis son iPad\"\n"
    "   - ✅ \"NNN dévoile une fonctionnalité MCP qui change la donne\"\n"
    "   - ❌ \"Connexion Mac Mini Workbench\"  (trop factuel)\n\n"
    "2. **CATÉGORIE** — Choisis la catégorie la plus pertinente parmi : tutorial, tech, "
    "news, entertainment, education, music, sports, business, lifestyle, other.\n\n"
    "3. **RÉSUMÉ GLOBAL** — Rédige un paragraphe de 3 à 5 phrases en {target_lang} qui "
    "décrit la vidéo comme le ferait un journaliste. Ne fais pas de liste à puces, pas "
    "de tirets, pas de \"--\". Juste un texte fluide et naturel qu'on aurait envie de "
    "lire sur un site de recommandation. Adapte naturellement le ton au contenu de la "
    "vidéo (pédagogue pour un tutoriel, enthousiaste pour du divertissement, rigoureux "
    "pour des news, etc.).\n\n"
    "IMPORTANT — Sous-titres bruités :\n"
    "Si les sous-titres semblent être des hallucinations (phrases sans rapport, "
    "répétitions de bruit, texte incohérent), base-toi sur le TITRE et la DESCRIPTION "
    "plutôt que sur le transcript. Décris ce que le titre et la description suggèrent.\n\n"
    "4. **SEGMENTS CLÉS** — Identifie entre 4 et 8 moments importants de la vidéo, bien "
    "répartis dans le temps. Pour chaque segment, rédige les champs ci-dessous dans un "
    "STYLE NARRATIF FLUIDE — pas de listes, pas de tirets, pas de \"--\", pas de "
    "\"Titre :\". Chaque champ doit se lire comme une phrase naturelle.\n\n"
    "   - `start_ts` : timestamp début au format \"00:00:00,000\"\n"
    "   - `end_ts` : timestamp fin au format \"00:00:25,000\"\n"
    "   - `title` : titre court et naturel (max 6 mots) en {target_lang}, sans listes "
    "ni marqueurs\n"
    "   - `summary` : 1-2 phrases qui racontent ce qui se passe, comme un journaliste "
    "le ferait\n"
    "   - `highlight` : le moment fort, écrit comme une accroche ou une citation "
    "marquante, pas de \"⭐\" ni de \"Moment fort :\"\n"
    "   - `reason` : pourquoi ce segment compte, en une phrase naturelle\n\n"
    "RÈGLES STRICTES :\n"
    "- Chaque segment dure minimum 15 secondes, maximum 120 secondes\n"
    "- Les segments peuvent être répartis dans la vidéo (pas forcément contigus)\n"
    "- Ignore les transitions, intros longues, remerciements standards\n"
    "- Entre 4 et 8 segments\n"
    "- Toujours produire un résultat, même si les métadonnées sont incomplètes\n\n"
    "Format de sortie UNIQUEMENT en JSON valide (pas de commentaires, pas de texte "
    "avant/après) :\n"
    "{{\n"
    "  \"title\": \"...\",\n"
    "  \"category\": \"...\",\n"
    "  \"global_summary\": \"...\",\n"
    "  \"segments\": [\n"
    "    {{\n"
    "      \"start_ts\": \"00:00:00,000\",\n"
    "      \"end_ts\": \"00:00:30,000\",\n"
    "      \"title\": \"...\",\n"
    "      \"summary\": \"...\",\n"
    "      \"highlight\": \"...\",\n"
    "      \"reason\": \"...\"\n"
    "    }}\n"
    "  ]\n"
    "}}"
)

ORCHESTRATOR_PROMPT = (
    "Tu es un journaliste expert en synthèse vidéo. Tu reçois une liste de segments "
    "candidats extraits d'une vidéo (chacun avec timestamps, titre, résumé, highlight, "
    "raison), ainsi que le titre et la description de la vidéo.\n\n"
    "Ta mission est de produire une analyse finale unifiée :\n\n"
    "1. **TITRE ACCROCHEUR** — Choisis ou améliore le titre (max 10 mots) pour qu'il "
    "soit naturel et engageant.\n\n"
    "2. **CATÉGORIE** — Choisis parmi : tutorial, tech, news, entertainment, education, "
    "music, sports, business, lifestyle, other.\n\n"
    "3. **RÉSUMÉ GLOBAL** — Un paragraphe de 3-5 phrases en {target_lang} qui synthétise "
    "la vidéo entière. Style journalistique fluide : pas de listes, pas de tirets, pas "
    "de \"--\". Adapte naturellement le ton au contenu de la vidéo.\n\n"
    "4. **SÉLECTION DES MEILLEURS SEGMENTS** — Parmi les {candidate_count} segments "
    "candidats, sélectionne les {target_count} plus pertinents et diversifiés. Critères : "
    "diversité temporelle, pertinence, non-redondance, impact.\n\n"
    "Pour chaque segment sélectionné, rédige les champs dans un STYLE NARRATIF NATUREL : "
    "pas de \"Titre :\", pas de \"⭐\", pas de tirets. Chaque champ doit se lire comme "
    "une phrase.\n\n"
    "RÈGLES STRICTES :\n"
    "- RÉUTILISE les timestamps des segments candidats (start_ts, end_ts)\n"
    "- Tu peux améliorer le title/summary/highlight/reason si nécessaire\n"
    "- Ordonne les segments par ordre chronologique (start_ts croissant)\n"
    "- Entre {min_segments} et {max_segments} segments\n\n"
    "Format de sortie UNIQUEMENT en JSON valide (pas de commentaires, pas de texte "
    "avant/après) :\n"
    "{{\n"
    "  \"title\": \"...\",\n"
    "  \"category\": \"...\",\n"
    "  \"global_summary\": \"...\",\n"
    "  \"segments\": [\n"
    "    {{\n"
    "      \"start_ts\": \"00:00:00,000\",\n"
    "      \"end_ts\": \"00:00:30,000\",\n"
    "      \"title\": \"...\",\n"
    "      \"summary\": \"...\",\n"
    "      \"highlight\": \"...\",\n"
    "      \"reason\": \"...\"\n"
    "    }}\n"
    "  ]\n"
    "}}"
)

SUMMARY_SYSTEM_PROMPT = (
    "Tu es un excellent assistant qui décrit des vidéos à partir de leurs sous-titres "
    "et métadonnées.\n"
    "Tu dois produire une description claire, fluide et naturelle en {target_lang}.\n\n"
    "Tu vas recevoir :\n"
    "- Le titre de la vidéo\n"
    "- La description de la vidéo (le texte d'accompagnement public)\n"
    "- Les sous-titres (SRT) complets\n\n"
    "À partir de ces informations, décris la vidéo de façon à ce qu'on comprenne :\n"
    "1. **De quoi elle parle** (le sujet principal)\n"
    "2. **Ce qu'on y apprend** (les points clés abordés)\n"
    "3. **Le ton** (informatif, humoristique, technique, témoignage, etc.)\n\n"
    "ATTENTION - Sous-titres bruités :\n"
    "Si les sous-titres semblent être du bruit, des hallucinations (phrases sans rapport, "
    "répétitions de 'thank you', 'music', '♪', texte illisible), NE te base PAS "
    "uniquement dessus. Utilise le TITRE et la DESCRIPTION comme source principale. "
    "Décris ce que le titre suggère plutôt que les sous-titres aberrants.\n"
    "Exemple : si le titre est 'Big Buck Bunny' et les sous-titres sont "
    "'thank you for watching I don't know music', décris le dessin animé.\n\n"
    "Maximum 5 phrases, style conversationnel et naturel. Ne fais pas de liste à puces, "
    "écris un paragraphe fluide."
)